// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR26yPutT8O2htucoix8Y4aOVbjyMVZR8',
    appId: '1:513830044932:web:5851150d80b4b083583c51',
    messagingSenderId: '513830044932',
    projectId: 'plantrip-7d4ec',
    authDomain: 'plantrip-7d4ec.firebaseapp.com',
    storageBucket: 'plantrip-7d4ec.firebasestorage.app',
    measurementId: 'G-1RN1FDT7QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGJmFWcXAA3wCvyL3dDTC4hJ1zN_tO3o8',
    appId: '1:513830044932:android:da4bda9af30ac55b583c51',
    messagingSenderId: '513830044932',
    projectId: 'plantrip-7d4ec',
    storageBucket: 'plantrip-7d4ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP47VMwD5vOY8tvPHW8U3D0_b_b0t5Bpk',
    appId: '1:513830044932:ios:2aa2eb987f68573f583c51',
    messagingSenderId: '513830044932',
    projectId: 'plantrip-7d4ec',
    storageBucket: 'plantrip-7d4ec.firebasestorage.app',
    iosBundleId: 'com.example.plantrip',
  );
}
